# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/minima',
                'doc_host': 'https://m0saan.github.io',
                'git_url': 'https://github.com/m0saan/minima',
                'lib_path': 'minima'},
  'syms': {'minima.core': {'minima.core.foo': ('autograd.html#foo', 'minima/core.py')}}}
