# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/09_minima_backend.ipynb.

# %% auto 0
# __all__ = []

# %% ../nbs/09_minima_backend.ipynb 2
import os
import numpy as np

# %% ../nbs/09_minima_backend.ipynb 3
BACKEND = os.environ.get("MINIMA_BACKEND", "mi")

if BACKEND == "mi":
    from . import ndarray as ARRAY_API
    from .ndarray import (
        all_devices,
        # cuda,
        # cpu,
        cpu_numpy,
        default_device,
        BackendDevice as Device,
    )

    NDArray = ARRAY_API.NDArray
elif BACKEND == "np":
    import numpy as ARRAY_API
    from .ndarray_backend_numpy import all_devices, cpu, default_device, Device

    NDArray = ARRAY_API.ndarray
else:
    raise RuntimeError("Unknown minima array backend %s" % BACKEND)