# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/07_ndarray_backend_numpy.ipynb.

# %% auto 0
__all__ = ['Array', 'to_numpy', 'from_numpy', 'fill', 'compact', 'ewise_setitem', 'scalar_setitem', 'ewise_add', 'scalar_add',
           'ewise_mul', 'scalar_mul', 'ewise_div', 'scalar_div', 'scalar_power', 'ewise_maximum', 'scalar_maximum',
           'ewise_eq', 'scalar_eq', 'ewise_ge', 'scalar_ge', 'ewise_log', 'ewise_exp', 'ewise_tanh', 'matmul',
           'reduce_max', 'reduce_sum']

# %% ../nbs/07_ndarray_backend_numpy.ipynb 2
import numpy as np

# %% ../nbs/07_ndarray_backend_numpy.ipynb 3
__device_name__ = "numpy"
_datatype = np.float32
_datetype_size = np.dtype(_datatype).itemsize

# %% ../nbs/07_ndarray_backend_numpy.ipynb 4
class Array:
    def __init__(self, size):
        self.array = np.empty(size, dtype=np.float32)

    def  __repr__(self):
        return self.array.__repr__()

    @property
    def size(self):
        return self.array.size

# %% ../nbs/07_ndarray_backend_numpy.ipynb 5
def to_numpy(a, shape, strides, offset):
    return np.lib.stride_tricks.as_strided(
        a.array[offset:], shape, tuple([s * _datetype_size for s in strides])
    )


def from_numpy(a: np.ndarray, out) -> None:
    out.array[:] = a.flatten()


def fill(out: Array, val) -> None:
    out.array.fill(val)


def compact(a, out, shape, strides, offset):
    out.array[:] = to_numpy(a, shape, strides, offset).flatten()


def ewise_setitem(a, out, shape, strides, offset):
    to_numpy(out, shape, strides, offset)[:] = a.array.reshape(shape)


def scalar_setitem(size, val, out, shape, strides, offset):
    to_numpy(out, shape, strides, offset)[:] = val


def ewise_add(a, b, out):
    out.array[:] = a.array + b.array


def scalar_add(a, val, out):
    out.array[:] = a.array + val


def ewise_mul(a, b, out):
    out.array[:] = a.array * b.array


def scalar_mul(a, val, out):
    out.array[:] = a.array * val


def ewise_div(a, b, out):
    out.array[:] = a.array / b.array


def scalar_div(a, val, out):
    out.array[:] = a.array / val


def scalar_power(a, val, out):
    out.array[:] = a.array ** power


def ewise_maximum(a, b, out):
    out.array[:] = np.maximum(a.array, b.array)


def scalar_maximum(a, val, out):
    out.array[:] = np.maximum(a.array, val)


def ewise_eq(a, b, out):
    out.array[:] = (a.array == b.array).astype(np.float32)


def scalar_eq(a, val, out):
    out.array[:] = (a.array == val).astype(np.float32)


def ewise_ge(a, b, out):
    out.array[:] = (a.array >= b.array).astype(np.float32)


def scalar_ge(a, val, out):
    out.array[:] = (a.array >= val).astype(np.float32)


def ewise_log(a, out):
    out.array[:] = np.log(a.array)


def ewise_exp(a, out):
    out.array[:] = np.exp(a.array)


def ewise_tanh(a, out):
    out.array[:] = np.tanh(a.array)


def matmul(a, b, out, m, n, p):
    out.array[:] = (a.array.reshape(m, n) @ b.array.reshape(n, p)).reshape(-1)


def reduce_max(a, out, reduce_size):
    out.array[:] = a.array[:].reshape(-1, reduce_size).max(axis=1)


def reduce_sum(a, out, reduce_size):
    out.array[:] = a.array[:].reshape(-1, reduce_size).sum(axis=1)
    
