# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/08_utility.ipynb.

# %% auto 0
__all__ = ['prod']

# %% ../nbs/08_utility.ipynb 2
import operator
import math
from functools import reduce

# %% ../nbs/08_utility.ipynb 3
def prod(x):
    return reduce(operator.mul, x, 1)
